registries:
  - name: pi_registry
    url: http://192.168.0.105:8081

brokers:
  - name: pi_broker
    bootstrap.servers: ${concat("192.168.0.105", ":", "9092")}
    registry: pi_registry
  - name: local_broker
    bootstrap.servers: 127.0.0.1:9092
    registry: pi_registry

environments:
  - name: pi
    onStart: |
      KAFKA_PREFIX=""
      KAFKA_LOCAL_CONTEXT="pi_broker"
      KAFKA_CENTRAL_CONTEXT=KAFKA_LOCAL_CONTEXT
      info("On Start script !")
    onEnd: info("On End script !")
  - name: local
    onStart: |
      KAFKA_PREFIX="local-"
      KAFKA_LOCAL_CONTEXT="local_broker"
      KAFKA_CENTRAL_CONTEXT="pi_broker"
